# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkcr < Formula
  desc "Create and list ServiceNow Standard Change requests without touching the UI"
  homepage "https://github.com/eimarfandino/snow-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_darwin_amd64.tar.gz"
      sha256 "c9ed4289a06ef279d24b4819731e3da063e7fc0cb68693dc475b2927dcb3cbb0"

      define_method(:install) do
        bin.install "mkcr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_darwin_arm64.tar.gz"
      sha256 "52a5a68333a1d297b251d9953cc63ce2807b6ca4ca3b1f8514aa96d1e233d169"

      define_method(:install) do
        bin.install "mkcr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_linux_amd64.tar.gz"
      sha256 "a86e5763d945cd8e835e499ad9a857228ab5c26d8dd946ee94a90aa9a4fcbe6d"
      define_method(:install) do
        bin.install "mkcr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_linux_arm64.tar.gz"
      sha256 "25edcec406584cf22379fb71b05e2dbcbd0df1928a2fb9d058824875fb828a2e"
      define_method(:install) do
        bin.install "mkcr"
      end
    end
  end

  test do
    system "#{bin}/mkcr", "--help"
  end
end
