# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkcr < Formula
  desc "Create and list ServiceNow Standard Change requests without touching the UI"
  homepage "https://github.com/eimarfandino/snow-cr-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_darwin_amd64.tar.gz"
      sha256 "1f0c7c7b31c79778c1ac043ae76d69198dd1fe4195f12818fef2eb31ec7abff8"

      define_method(:install) do
        bin.install "mkcr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_darwin_arm64.tar.gz"
      sha256 "dd02d7980c62ef6fc027599c6601e47e7198192484456c2311836965fe28357b"

      define_method(:install) do
        bin.install "mkcr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_linux_amd64.tar.gz"
      sha256 "92a63978026e477e49f497118d465c3b1432b66bf55d35fceefd7d4509584fc1"
      define_method(:install) do
        bin.install "mkcr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eimarfandino/snow-cli/releases/download/v0.0.2/snow-cli_linux_arm64.tar.gz"
      sha256 "3b76b6aa9a4a201d90b73eb6904344a25f86d87e93c2975b64e2b56844776942"
      define_method(:install) do
        bin.install "mkcr"
      end
    end
  end

  test do
    system "#{bin}/mkcr", "--help"
  end
end
